### ISSUE TITLE
Add "checks" to the validation chain depending on params (migrating to V4).

### ISSUE THREAD

**Issue by emipc** [ctavan/express-validator#497] opened 2018-01-19 12:36 UTC
I'm currently migrating my V3 code to V4 and I don't know how to deal with conditionals when using the check validation chain.

This is a function I currently have to validate params (working):

```
utils.checkUserRequestParams = (req) => {
	req.checkBody('user_id', 'Invalid user_id.').isInt();

	switch (req.body.role) {
		case 'student':
			req.checkBody('student.school.id', 'Invalid student.school.id.').optional().isInt();
			req.checkBody('student.school.name', 'Invalid student.school.name.').optional().notEmpty();

			break;
		case 'teacher':
			req.checkBody('teacher.school.id', 'Invalid teacher.school.id.').optional().isInt();
			req.checkBody('teacher.school.name', 'Invalid teacher.school.name.').optional().notEmpty();
			req.checkBody('teacher.school.classname', 'Invalid teacher.school.classname.').optional().notEmpty();
	}
}
```

Is there any way we can add "checks" to the validation chain depending on an specific condition (in this case, depending on the role I'll recieve different params)?

**Comment by gustavohenke** [comment] 2018-01-19 12:55
Duplicate of #439

**Closed by gustavohenke** 2018-01-19 12:56 UTC
