### ISSUE TITLE
Option to stop cascade validation on first fail

### ISSUE THREAD

**Issue by Zignd** [ctavan/express-validator#236] opened 2016-06-03 20:07 UTC
I have the following validation:

```
req.checkHeaders("tf-secret-key", "Invalid TF-Secret-Key.")
  .notEmpty()
    .withMessage("Missing HTTP TF-Secret-Key header.")
  .isValidTfSecretKey();
```

It's working as expected, the first validation function (`notEmpty`) is called followed by the second one (`isValidTfSecretKey`).

But the thing is, I'd like to prevent the cascading to the second validation function if the first one fails. Does express-validator allows that?

I checked the source code looking for something that could possibly allow me to do that but I could not find anything except for this verification on the `skipValidating` variable:

```
function makeValidator(methodName, container) {
  return function() {
    if (this.skipValidating) {
      return this;
    }
    // more code...
```

But it can't be accessed from the outside and is being used for another purpose.

**Comment by srkimir** [comment] 2016-06-24 00:15
@Zignd please check discussion in https://github.com/ctavan/express-validator/issues/235
i will close this one as duplicate of https://github.com/ctavan/express-validator/issues/235

**Closed by srkimir** 2016-06-24 00:15 UTC
