### ISSUE TITLE
Add notNull 

### ISSUE THREAD

**Issue by zatziky** [ctavan/express-validator#443] opened 2017-10-03 12:01 UTC
I haven't found a simple option how to express `notNull` but using `custom()`. Is there another way? If not, I'd like to this issue a feature request.

**Comment by numa001** [comment] 2017-10-21 07:35
try   .isLength({ min: 1 })

**Comment by zatziky** [comment] 2017-10-28 14:11
@numa001 jup it could work but it's much nicer to read `.isNull()` or `.isNotNull()`, isn't it?

**Comment by gustavohenke** [comment] 2018-02-06 11:56
Duplicate of #473

**Comment by gustavohenke** [comment] 2018-02-06 11:56
Semantics of #473 sound better to me, so I'm closing here in favor of that one.

**Closed by gustavohenke** 2018-02-06 11:56 UTC

**Comment by sant123** [comment] 2018-02-10 06:35
Also you can use `.not().isEmpty().withMessage("The field cannot be empty")`
