### ISSUE TITLE
GMT validator deprecated

### ISSUE THREAD

**Issue by mathewmeconry** [ctavan/express-validator#224] opened 2016-03-29 15:03 UTC
Hi 

after a npm update I receive following warning from your module:

> GMT validator deprecated you tried to validate a undefined but this library (validator.js) validates strings only. Please update your code as this will be an error soon. at node_modules/express-validator/lib/express_validator.js:338:41

npm version shows me following

> npm: '3.5.3',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.5.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' 

I use node v5.5.0

Thanks for your help

**Comment by rustybailey** [comment] 2016-03-29 15:22
Dupe of https://github.com/ctavan/express-validator/issues/219. Also, we plan on fixing this when we upgrade validator.js in https://github.com/ctavan/express-validator/issues/214. Right now it is just a warning, so it shouldn't be breaking anything.

**Closed by rustybailey** 2016-03-29 15:22 UTC
