### ISSUE TITLE
Why sanitizer doesn't support ['p1', 'p2'] parametor

### ISSUE THREAD

**Issue by Pana** [ctavan/express-validator#172] opened 2015-09-17 03:47 UTC
This will very helpful when deal multiple params

**Comment by rustybailey** [comment] 2015-09-17 13:16
Currently the array syntax is used to sanitize nested params (for example, using `['foo', 'bar', 'baz']` used to sanitize `foo.bar.baz`). We don't currently have a way to sanitize multiple params with a single method. Duplicate of issue https://github.com/ctavan/express-validator/issues/66.

**Closed by rustybailey** 2015-09-17 13:16 UTC
Labels: question
