### ISSUE TITLE
optional() method only works if the specified parameter is missing not if its empty

### ISSUE THREAD

**Issue by Bladedanxa** [ctavan/express-validator#140] opened 2015-06-15 01:48 UTC
I am using express-validator to parse my web form submissions and I wanted to apply a validator only if a value was submitted.  Unfortunately the optional() method did not seem to work as I expected and so I dug deeper.  What I found suggests to me that the optional() method only works if there is no parameter of the specified name submitted with the form.  Unfortunately it is not working if the value is submitted but is empty.

Am I using this method incorrectly?  Is this intended behavior?

**Comment by rustybailey** [comment] 2015-06-15 02:12
Correct. The intended behavior of "optional" is to only validate the property if it exists. Based #120, it seems like we may want to add another method that does the normal optional check and also checks if the value is truthy, since I would rather not change the functionality of the original "optional". Closing as a dupe of #120.

**Closed by rustybailey** 2015-06-15 02:12 UTC
