### ISSUE TITLE
oneOf inside another oneOf

### ISSUE THREAD

**Issue by emipc** [ctavan/express-validator#499] opened 2018-01-19 13:48 UTC
I'm getting this error:

> Cannot match against 'undefined' or 'null'. (from /express-validator/check/select-fields.js:71:33)

When using a oneOf inside another one. Like this:

```
oneOf([
  [
    check('role').equals('student'),
    check('student.school.id', 'Invalid student.school.id.').isInt(),
  ], [
    check('role').equals('teacher'),
    check('teacher.school.id', 'Invalid teacher.school.id.').isInt(),
    oneOf([
      [
        check('teacher.classes').exists(),
        check('teacher.classes.*.id', 'Invalid teacher.classes.*.id').isInt(),
      ],
      [/* Do nothing (no classes found) */]
    ])
  ]
])
```

If a remove the oneOf within the parent one, it works. Maybe I'm doing something wrong? I just want to check the classes (array of objects) in case they are found.

I'm using version 4.3.0.

**Comment by gustavohenke** [comment] 2018-01-23 13:35
Duplicate of #439

**Comment by gustavohenke** [comment] 2018-01-23 13:38
Nested `oneOf` calls aren't supported.

Also note that `teacher.classes.*.id` already requires every item under `teacher.classes` to have an `id` that validates. If none exists, then you're golden.

**Closed by gustavohenke** 2018-01-23 13:38 UTC

**Comment by emipc** [comment] 2018-01-24 09:33
Ok, then I'll stick with V3 as it handles this kind of situation easily.

**Comment by gustavohenke** [comment] 2018-01-24 09:43
Can you be clear about what you mean? I gave you an alternative that is simpler and still works compared to the original code.

**Comment by emipc** [comment] 2018-01-24 09:44
This is what is working for me right now:

```
switch (req.body.role) {
	case 'student':
		req.checkBody('student.school.id', 'Invalid student.school.id.').isInt();
		break;
	case 'teacher':
		req.checkBody('teacher.school.id', 'Invalid teacher.school.id.').isInt();

		if (req.body.teacher.classes.length) {
			req.body.teacher.classes.forEach((e, i) => {
				req.checkBody(`teacher.classes[${i}].id`, `Invalid teacher.classes[${i}].id`).isInt();
			});
		}
		break;
	default:
}
```

**Comment by gustavohenke** [comment] 2018-01-24 09:56
Right. There's no difference between the 2 snippets, they work exactly the same.

Anyway, a new major release is coming soon, and conditional validation will be available in the package.

**Comment by GhassenRjab** [comment] 2018-08-30 15:39
@gustavohenke 
Can I use a `oneOf` inside another `oneOf`? or this feature is not supported yet?
