### ISSUE TITLE
Skip Validation method

### ISSUE THREAD

**Issue by micheleValex** [ctavan/express-validator#225] opened 2016-04-07 19:30 UTC
hi, is possible skip validation not only for notEmpty
for example skip current validation if there are validationErrors in the req

thanks

**Comment by srkimir** [comment] 2016-06-24 00:23
hi @micheleValex 
please check discussion in https://github.com/ctavan/express-validator/issues/235
Will close this one as duplicate of https://github.com/ctavan/express-validator/issues/235

**Closed by srkimir** 2016-06-24 00:23 UTC
