### ISSUE TITLE
`custom()` validation not working

### ISSUE THREAD

**Issue by KrashLeviathan** [ctavan/express-validator#505] opened 2018-01-23 04:10 UTC
Here's an abstract of the code I'm working with:

```javascript
import { check } from 'express-validator/check';

router.post(
  '/myendpoint',
  [
    check('myparameter', 'This should be hardcoded to fail')
      .custom((value, { req }) => {
        console.log(value);
        return false;
      })
  ],
  myEndpointHandler
);
```
I'm using a custom check to validate a query parameter, and after trying everything to get it to work, I distilled it down to something that looks just like the code [in the documentation](https://github.com/ctavan/express-validator#validation-chain-api), and it still won't work. It's not asynchronous, it's just a boolean check. I took out my boolean check and hardcoded in `false`, but it still doesn't work. I'm running it with v4.3.0. I added the `console.log(value)` and it's printing the correct value that gets passed in. Is there something I'm missing, or is `custom()` not fully working, or is the documentation out of date?

Thanks!

**Comment by gustavohenke** [comment] 2018-01-23 10:03
How are your requests being made?

**Comment by KrashLeviathan** [comment] 2018-01-23 17:00
HTTP via Firefox RESTClient using `Content-Type: application/json` header. The body of the request is `{ "myparameter": "some value" }`.

**Comment by gustavohenke** [comment] 2018-01-23 22:53
This isn't sounding good.
Can you share a minimal reproducible project, so I can see if there's anything with your setup?

**Comment by valeco** [comment] 2018-01-26 14:34
I'm struggling with the exact same problem! [I just asked a question on StackOverflow about this.](https://stackoverflow.com/questions/48463157/express-validator-custom-method-doesnt-work-how-to-debug-it) :man_facepalming:

I'm using a custom validation just like @KrashLeviathan does:

```js
router.post('/person/add',
  personController.validateData, 
  asyncHandler(personController.createPerson)
)
```

```js
exports.validateData = [

  // ...Other built-in validations that work...

  body('field')
    .custom((value) => {
      console.log('This message shows up!')
      return false
    })
    .withMessage('Wrong!'),

  // ...Other built-in validations that work...
]
```

I never get the 'Wrong!' flash message.

Any idea why this is happening? I don't actually know how to debug it. :disappointed:

**Comment by KrashLeviathan** [comment] 2018-01-26 21:20
Sure. The project is open source, so you can take a look at the project setup here: [https://github.com/hammer-io/yggdrasil](https://github.com/hammer-io/yggdrasil). (It's still **very much** under development, so take things with a grain of salt!) The `endor` folder has our backend code, and that's where I was trying to run the validation. I ended up using a regular node validation construct instead of using `check`. The place I was trying to use it was in `endor/src/routes/invites.routes.js`, in the POST endpoint to invite a new contributor. We usually have all the validation in middleware, but when I was trying to debug it I essentially replaced the route at approx. line 105 with the following:

```javascript
router.post(
  '/projects/:projectId/invites/:user',
  [
    check('daysFromCreationUntilExpiration', 'This should be hardcoded to fail')
      .custom((value, { req }) => {
        console.log(value);
        return false;
      })
  ],
  invitesController.addInviteToProject
);
```

I hope that's enough information to try to track down the issue (or to point out what I was doing wrong). :-)

**Comment by gustavohenke** [comment] 2018-01-27 02:41
Hey guys, so I checked both of your codes and they both work.

@valeco I added a `console.log(req.flash())` to your error handler and it prints all messages, including `Wrong!` 😉 

@KrashLeviathan I replaced that route with the following:

```js
router.post(
  '/foo',
  // authController.isAuthenticated,
  check('daysFromCreationUntilExpiration', 'This should be hardcoded to fail')
      .custom((value, { req }) => {
        console.log(value);
        return false;
      }),
  (req, res, next) => {
    const errors = validationResult(req).mapped();
    res.json({ errors });
  }
);
```

You were probably missing the call to `validationResult`.

Will close the issue for now. Feel free to continue the discussion.

**Closed by gustavohenke** 2018-01-27 02:41 UTC

**Comment by valeco** [comment] 2018-01-27 04:50
Hey @gustavohenke, thank you so much for spend your time on this and for your quick response!

You're right, the `Wrong!` message is printed but **only when another validation fail** (at least one of them), otherwise custom validation gets ignored (as if the `return false` wasn't there).

In my case, if you fill the fields `nombre`, `horas` and `ano`, the `Wrong!` message doesn't appear. You can try it in your browser on `localhost:3000/materias/agregar`. _(Flash messages are printed between the curly brackets above the form.)_

**Comment by gustavohenke** [comment] 2018-01-27 09:54
Sorry @valeco but I still can't reproduce. I commented out the other validators and sanitisers and it still works. I must also comment that I had to remove the mongoose connection.

Can you *please* create a minimal example that reproduces your issue?
